config/routes.rb
Rails.application.routes.draw do
  resources :trackers, except: :show
  resources :projects, except: :show
  root 'trackers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/user_scopes_concern.rb
require 'active_support/concern'

module UserScopesConcern
  extend ActiveSupport::Concern

  included do
    scope :by_user, ->(user) { where(user_id: user.id) }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include UserScopesConcern
  has_many :trackers
  belongs_to :user

  def color
    self[:color] || '#FF0000'
  end
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  include UserScopesConcern
  belongs_to :user
  belongs_to :project

  validates :logged_date, presence: true
  validates :duration, presence: true
  validates :description, presence: true
  validates :project, presence: true
  validates :user, presence: true

  scope :by_logged_date, -> { order(logged_date: :desc) }

  validate :duration_must_be_readable
  before_save :set_duration_time

  def project_name
    project.name if project
  end

  private

  def duration_must_be_readable
    return unless duration
    chronic_duration = Chronic::Duration.for(duration)
    if chronic_duration.is_a? Chronic::ExceptionalValue
      errors.add(:duration, :invalid, message: chronic_duration.reason)
    end
  end

  def set_duration_time
    self.duration_time = Chronic::Duration.for(duration).to_seconds
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :trackers
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def record_not_found
    render plain: '404 Not Found', status: 404
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: [:edit, :update, :destroy]
  after_action :verify_authorized, except: [:index, :new, :create]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.by_user(current_user).all
    @project = Project.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params.merge(user: current_user))
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by!(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {}).permit(:name, :color)
    end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :require_login
  before_action :set_tracker, only: [:edit, :update, :destroy]
  after_action :verify_authorized, except: [:index, :new, :create]

  # GET /trackers
  # GET /trackers.json
  def index
    @project_charts = ProjectChart.for(user: current_user, date: Date.today)
    @trackers = Tracker.by_user(current_user).by_logged_date.all
    @tracker = Tracker.new
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
    authorize @tracker
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params.merge(user: current_user))
    respond_to do |format|
      if @tracker.save
        format.html { redirect_to trackers_url, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    authorize @tracker
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to trackers_url, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    authorize @tracker
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tracker
    @tracker = Tracker.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tracker_params
    params.fetch(:tracker, {}).permit(:duration, :description, :project_id, :logged_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_li_link_to(name = nil, url = nil, html_options = {}, options = nil)
    active_class = html_options[:active] || 'active'
    html_options.delete(:active)
    li_html_class = active_class if current_page?(options)
    content_tag :li, class: li_html_class do
      link_to(name, url, html_options)
    end
  end

  def materialize_class_for(flash_type)
    case flash_type.to_sym
    when :success
      'teal'
    when :error
      'red'
    when :alert
      'orange'
    when :notice
      'blue'
    else
      'grey'
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper

  def project_chart_data(date, project_charts)
    charts = project_charts.select { |p| p.logged_date == date}
    charts.map(&:duration)
  end

  def project_chart_duration(date, project_charts)
    charts = project_charts.select { |p| p.logged_date == date}
    duration = charts.inject(0) { |sum, n| sum + n.duration.to_i }
    return '' unless duration
    Chronic::Duration.new(duration).humanize
  end

  def project_chart_color(date, project_charts)
    charts = project_charts.select { |p| p.logged_date == date}
    charts.map(&:color)
  end

  def project_chart_label(date, project_charts)
    charts = project_charts.select { |p| p.logged_date == date}
    charts.map { |p| ''}
  end
end

app/helpers/tracker_helper.rb
module TrackerHelper
  def tracker_duration(duration)
    return time_ago_in_words(Time.current - duration) if duration.is_a? Integer
    ''
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="card-panel <%= materialize_class_for(type) %>">
    <span class="white-text"><%= message %></span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <nav class="container z-depth-2">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">RataTime</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <% if signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <%= active_li_link_to 'Trackers', trackers_path, {}, {controller: 'trackers'} %>
            <%= active_li_link_to 'Projects', projects_path, {}, {controller: 'projects'} %>
            <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <%= active_li_link_to 'Trackers', trackers_path, {}, {controller: 'trackers'} %>
            <%= active_li_link_to 'Projects', projects_path, {}, {controller: 'projects'} %>
            <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="section container page-title z-depth-2">
      <%= yield :page_title %>
    </div>
    <div class="container section content z-depth-2">
      <div class="row">
        <div class="col s8 push-s2">
          <%= render partial: "layouts/flash_messages", flash: flash %>
        </div>
      </div>
      <%= yield %>
    </div>
    <%= yield :charts_js %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :color, as: :color, input_html: { default_value: "#FF0000"} %>
  <%= f.button :submit %>
  <%= link_to "Cancel", :back, class: "modal-action modal-close waves-effect waves-green btn-flat"%>
<% end %>

app/views/projects/edit.html.erb
<% content_for :page_title do %>
  <h5>Editing Project</h5>
<% end %>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<% content_for :page_title do %>
  <h5>Projects</h5>
<% end %>

<div class="section rtt-table">
  <table class="table">
    <tbody>
      <% @projects.each do |project| %>
        <tr class="js-clickable-row" data-href= "<%= edit_project_path(project) %>">
          <td><div class="tag-color" style= "background-color: <%= project.color %>"></div><b><%= project.name %></b></td>
          <td class="actions right-align hide-on-med-and-down">
            <%= link_to raw('<i class="material-icons">mode_edit</i>'), edit_project_path(project), id: "rat-edit-project-#{project.id}", class: 'text-warning' %>
            <%= link_to raw('<i class="material-icons">delete</i>'), project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!-- Button tracker creation -->
  <div class="fixed-action-btn" style="bottom: 45px; right: 40px;">
    <a class="btn-floating btn-large red">
      <i class="material-icons">add</i>
    </a>
    <ul>
      <li><a class="btn-floating blue hide-on-med-and-down modal-trigger" style="transform: scaleY(0.4) scaleX(0.4) translateY(40px) translateX(0px); opacity: 0;" href="#new-project"><i class="material-icons">web</i></a></li>
      <li><a class="btn-floating blue modal-trigger hide-on-large-only" style="transform: scaleY(0.4) scaleX(0.4) translateY(40px) translateX(0px); opacity: 0;" href="/projects/new"><i class="material-icons">web</i></a></li>
    </ul>
  </div>
  <!-- end button -->

</div>

<!-- Modal Structure -->
<div id="new-project" class="modal">
  <%= simple_form_for @project do |f| %>
    <div class="modal-content">
      <h4>Create a project</h4>
        <%= f.input :name %>
        <%= f.input :color, as: :color, input_html: { default_value: "#FF0000"} %>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
      <%= f.button :submit %>
    </div>
  <% end %>
</div>
<!-- End Modal Structure -->

app/views/projects/new.html.erb
<% content_for :page_title do %>
  <h5>New Project</h5>
<% end %>

<%= render 'form', project: @project %>

app/views/trackers/_form.html.erb
<%= simple_form_for @tracker do |f| %>
  <%= f.input :logged_date, as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :duration %>
  <%= f.association :project, collection: current_user.projects.order(:name), prompt: "Choose a Project" %>
  <%= f.input :description %>
  <%= f.button :submit %>
  <%= link_to "Cancel", :back, class: "modal-action modal-close waves-effect waves-green btn-flat"%>
<% end %>

app/views/trackers/edit.html.erb
<% content_for :page_title do %>
  <h5>Editing Tracker</h5>
<% end %>

<%= render 'form', tracker: @tracker %>

app/views/trackers/index.html.erb
<% content_for :page_title do %>
  <h5>Trackers</h5>
<% end %>

<div id="rtt-last-five-days" class="section hide-on-med-and-down">
  <table class= "table" style="text-align: center">
    <thead>
      <tr>
        <% ((4.days.ago.to_date)..(DateTime.now.to_date)).each do |day| %>
        <th class="center-align"><%= day %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr class="center-align">
        <% ((4.days.ago.to_date)..(DateTime.now.to_date)).each do |day| %>
          <td>
            <div style="width: 150px; margin:auto">
              <canvas class="js-tracker-day-chart"
                      data-labels='<%= raw project_chart_label(day, @project_charts) %>',
                      data-values='<%= project_chart_data(day, @project_charts) %>'
                      data-colors='<%= project_chart_color(day, @project_charts) %>'
                      data-title='<%= project_chart_duration(day, @project_charts) %>'>
              </canvas>
            </div>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<div class="divider"></div>

<div id="rtt-log-entries" class="rtt-table section">
  <table class= "table borderless">
    <tbody>
      <% @trackers.each do |tracker| %>
        <tr class="js-clickable-row" data-href= "<%= edit_tracker_path(tracker) %>">
          <td><div style="padding:0 0 0 2px;border-left: 3px solid <%= tracker.project.color %>"><i><%= tracker.duration %></i></div></td>
          <td>
            <span><b><%= tracker.project_name %></b></span><br />
            <span class="tracker-description"><%= tracker.description %></span>
          </td>
          <td class="right-align"><i><%= l tracker.logged_date, format: "%Y/%m/%d" %></i></td>
          <td class="actions right-align hide-on-med-and-down">
            <%= link_to raw('<i class="material-icons">mode_edit</i>'), edit_tracker_path(tracker), id: "rat-edit-tracker-#{tracker.id}", class: 'text-warning ' %>
            <%= link_to raw('<i class="material-icons">delete</i>'), tracker, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Button tracker creation -->
  <div class="fixed-action-btn" style="bottom: 45px; right: 40px;">
    <a class="btn-floating btn-large red">
      <i class="material-icons">add</i>
    </a>
    <ul>
      <li><a class="btn-floating blue hide-on-med-and-down modal-trigger" style="transform: scaleY(0.4) scaleX(0.4) translateY(40px) translateX(0px); opacity: 0;" href="#new-tracker"><i class="material-icons">schedule</i></a></li>
      <li><a class="btn-floating blue modal-trigger hide-on-large-only" style="transform: scaleY(0.4) scaleX(0.4) translateY(40px) translateX(0px); opacity: 0;" href="/trackers/new"><i class="material-icons">schedule</i></a></li>
    </ul>
  </div>
  <!-- end button -->
</div>

<!-- Modal Structure -->
<div id="new-tracker" class="modal modal-fixed-footer">
  <%= simple_form_for @tracker do |f| %>
    <div class="modal-content">
      <h4>Create a tracker</h4>
        <%= f.input :logged_date, as: :string, input_html: { class: "datepicker" } %>
        <%= f.input :duration %>
        <%= f.association :project, collection: current_user.projects.order(:name), prompt: "Choose a Project" %>
        <%= f.input :description %>

    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
      <%= f.button :submit %>
    </div>
  <% end %>
</div>
<!-- End Modal Structure -->

app/views/trackers/new.html.erb
<% content_for :page_title do %>
  <h5>New Tracker</h5>
<% end %>
<%= render 'form', tracker: @tracker %>

app/views/users/_form.html.erb
<%= form.text_field :email, type: 'email', placeholder: 'Email address', class: 'form-control'  %>
<%= form.password_field :password, placeholder: 'Password', class: 'form-control' %>

app/views/users/new.html.erb
<%= form_for @user, html: {class: 'form-signin'} do |form| %>
  <h2><%= t(".title") %></h2>
  <%= render partial: '/users/form', object: form %>
  <%= form.submit class: 'btn btn-lg btn-primary btn-block' %>
  <div class="other-links">
    <%= link_to t(".sign_in"), sign_in_path %>
  </div>
<% end %>